services:
#    mm_platform.example:
#        class: MM\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    mm_platform.antispam:
        class: MM\PlatformBundle\AntiSpam\MMAntiSpam
        arguments:
            - "@mailer"
            - %locale%
            - 50

